language: node_js
node_js:
  - "10.9"

install:
  - npm install
script:
  - npm run el-build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change